---

- hosts: all

  tasks:

    - name: Start postgres
      become: true
      service:
        name: postgresql
        state: started

    - name: Change permissions on start script
      become: true
      command: sudo chmod -R u+rwx "/home/{{ user }}/csle/ansible/start.sh"

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Debug resolved path
      debug:
        msg: "python /home/{{ user }}/csle/ansible/start_services.py {{ leader_ip }} {{ user }} {{ conda_environment_name }}"

    - name: Check file existence
      stat:
       path: "/home/kim/csle/ansible/start_services.py"
      register: script_file

    - name: Execute start script on the leader node
      command: "python /home/{{ user }}/csle/ansible/start_services.py {{ leader_ip }} {{ user }} {{ conda_environment_name }}"
      become: true
      become_user: "{{ user }}"

    - name: Execute start scripts on the worker nodes
      command: "python /home/{{ user }}/csle/ansible/start_services.py {{ item }} {{ user }} {{ conda_environment_name }}"
      loop: "{{ groups['worker'] }}"
      become: true
      become_user: "{{ user }}"