name: python-build
run-name: ${{ github.actor }} python build
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Tox tests csle-agents
        run: cd simulation-system/libs/csle-agents; tox
      - name: Tox tests csle-attacker
        run: cd simulation-system/libs/csle-attacker; tox
      - name: Tox tests csle-collector
        run: cd simulation-system/libs/csle-collector; tox
      - name: Tox tests csle-common
        run: cd simulation-system/libs/csle-common; tox
      - name: Tox tests csle-defender
        run: cd simulation-system/libs/csle-defender; tox
      - name: Tox tests csle-ryu
        run: cd simulation-system/libs/csle-ryu; tox
      - name: Tox tests csle-system-identification
        run: cd simulation-system/libs/csle-system-identification; tox
      - name: Tox tests gym-csle-stopping-game
        run: cd simulation-system/libs/gym-csle-stopping-game; tox